base_url = "https://yihong0618.github.io/gitblog/"
generate_feeds = true
feed_filenames = ["rss.xml"]
theme = "even"
taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]
[extra]
even_title = "yihong0618's Blog"
even_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/tags/yi-xie-ji-lu/", name = "一些记录"}},
]
