name: Generate GitBlog README

on:
  workflow_dispatch:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  push:
    branches:
      - master
    paths:
      - main.py

env:
  GITHUB_NAME: yihong0618
  GITHUB_EMAIL: zouzou0208@gmail.com
  BACKUP_BRANCH: backup

jobs:
  sync:
    name: Generate README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: Checkout Blog
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BACKUP_BRANCH }}
          path: back

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
          cache: 'pip'

      - name: Get pip env
        run: |
          python -m pip install --upgrade pip
          pip install -r main/requirements.txt
      - name: Generate new md # if you fork or clone this repo, please delete the curl line unless you know why
        run: cd back && python ../main/main.py ${{ secrets.G_T }} ${{ github.repository }} --issue_number '${{ github.event.issue.number }}'

      - name: Push README
        run: |
          cp back/README.md main/README.md
          cp back/feed.xml main/feed.xml
          cd main
          git config --local user.email "${{ env.GITHUB_EMAIL }}"
          git config --local user.name "${{ env.GITHUB_NAME }}"
          git add README.md feed.xml
          git commit --amend --no-edit
          git push --force
          cd ../back
          git config --local user.email "${{ env.GITHUB_EMAIL }}"
          git config --local user.name "${{ env.GITHUB_NAME }}"
          git add .
          git commit -m "update new blog"
          git push
